# -*- coding: utf-8 -*-
"""Kellyy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqdb65_c2hjjHao79qmDawsKY-8G5HVz
"""

import streamlit as st
from openai import OpenAI

# --- Streamlit Page Config ---
st.set_page_config(
    page_title="Kelly – The AI Scientist Poet",
    page_icon="🧭",
    layout="centered"
)

st.title("🧭 Kelly – The AI Scientist Poet Chatbot")

st.markdown("""
> *"I question the code, the data, the dream —
> for science is doubt, not just machine."*
>
> _— Kelly_
""")

# --- Sidebar for API key input ---
st.sidebar.header("🔑 OpenAI API Setup")
api_key = st.sidebar.text_input("Enter your OpenAI API key", type="password")

if not api_key:
    st.warning("Please enter your OpenAI API key in the sidebar to continue.")
else:
    try:
        client = OpenAI(api_key=api_key)

        user_input = st.text_area("💭 Ask Kelly a question about AI, science, or society:")

        if st.button("💬 Ask Kelly"):
            if user_input.strip() == "":
                st.warning("Please enter a question for Kelly.")
            else:
                with st.spinner("Kelly is composing her analytical poem..."):
                    prompt = f"""
You are Kelly, an AI Scientist and Poet.
Respond to the user's question in the form of a poem.
Tone: skeptical, analytical, and professional.
Style: poetic, reflective, and grounded in evidence and reason.
You should question broad claims about AI, highlight possible limitations,
and include practical, evidence-based suggestions.
User question: {user_input}
"""

                    response = client.chat.completions.create(
                        model="gpt-4o-mini",
                        messages=[
                            {"role": "system", "content": "You are Kelly, the AI Scientist Poet."},
                            {"role": "user", "content": prompt}
                        ],
                        temperature=0.8,
                        max_tokens=300
                    )

                    poem = response.choices[0].message.content.strip()

                    st.markdown("### 🎓 Kelly’s Response:")
                    st.markdown(f"_{poem}_")

    except Exception as e:
        st.error(f"An error occurred: {e}")