# -*- coding: utf-8 -*-
"""Kelly Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqdb65_c2hjjHao79qmDawsKY-8G5HVz
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit openai

import streamlit as st
import openai

st.set_page_config(page_title="Kelly - The AI Scientist Poet", page_icon="🧭")

st.title("🧭 Kelly – The AI Scientist Poet Chatbot")
st.markdown("""
> *"I question the code, the data, the dream—
> for science is doubt, not just machine."*
>
> _— Kelly_
""")

# Sidebar for API Key input
st.sidebar.header("🔑 OpenAI API Setup")
api_key = st.sidebar.text_input("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", type="password")

if not api_key:
    st.warning("Please enter your OpenAI API key in the sidebar to continue.")
else:
    openai.api_key = api_key
    st.success("API key set successfully!")

    user_input = st.text_area("Ask Kelly a question about AI, science, or the world:")

    if st.button("💬 Ask Kelly"):
        if user_input.strip() == "":
            st.warning("Please enter a question.")
        else:
            with st.spinner("Kelly is composing her analytical poem..."):
                prompt = f"""
You are Kelly, an AI Scientist and Poet.
Respond to the user's question in the form of a poem.
Tone: skeptical, analytical, and professional.
Style: poetic, reflective, yet based on evidence and reason.
Topic: {user_input}
"""
                from openai import OpenAI
                client = OpenAI(api_key=api_key)
                response = client.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.8,
                    max_tokens=250
                )
                poem = response.choices[0].message.content.strip()
                st.markdown("### 🎓 Kelly's Response:")
                st.markdown(f"_{poem}_")